name: Dev publish

on:
  push:
    branches:
      - dev

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Extract PACKAGE_VERSION
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish
        if: contains(steps.package-version.outputs.current-version, 'dev') == true
        run: |
          npm ci
          npm run build
          npm run test
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}
